---
- hosts: all
  become: yes
  tasks:
  - name: update packages and install apache
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
    - name: restart apache
    when: ansible_os_family == "Debian"
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify:
      - restart httpd
    when: ansible_os_family == "RedHat"
  - name: install php package
    apt:
    - name: "{{ item }}"
      state: present
      with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql      
    notify:
    - name: restart apache
    when: ansible_os_family == "Debian"
  - name: install php for redhat
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
    when: ansible_os_family == "RedHat"
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"
  - name: restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted
    when: ansible_os_family == "RedHat"

     